config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :welcome, only: [:index]
  namespace :welcome do
    post 'process_form'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user_input
  end

  def process_form
    @user_input = params[:user_input]
    render :index


    yodatranslate = HTTParty.get("https://yoda.p.mashape.com/yoda?sentence=#{@user_input}", headers:{"X-Mashape-Key" => "5LWnhavymkmsh6qvJgKB31zRESQ6p1tjcwUjsnjVgqZE80gBPD","Accept" => "text/plain"})

  end

end

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wordament</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
      Wordament
    </header>
    <p> This is the body of the app </p>
    <%= form_tag(welcome_process_form_path) do %>
        <%= label_tag(:word_string, "Enter the word you wish to translate") %>
        <%= text_field_tag :user_input %>
        <%= submit_tag 'click to translate', :id=> "submit" %>
    <% end %>
    <% unless @user_input.nil? %>
    <%= "You entered #{@user_input}" %>
    <% end %>

</body>
</html>